### ISSUE TITLE
MySQL Driver

### ISSUE THREAD

**Issue by mattes** [mattes/migrate#1]

**Comment by mattes** [comment]
see also https://github.com/mattes/migrate/pull/39

**Comment by raphaeljlps** [comment]
hey @mattes what do you think about mymysql ? (github.com/ziutek/mymysql)
I am thinking about implementing a Driver interface for it, do you think is worth ?

**Comment by arnehormann** [comment]
For cases like yours, you can also use the driver by its database/sql/driver interface (`mysql.MySQLDriver{}.Open(dsn)`).
That way, you get a single-connection session instead of a connection pool - with a little more setup boilerplate.
I think there's some ORM tools already doing so.

**Comment by mattes** [comment]
I never used it, but https://github.com/ziutek/mymysql#example-4---multi-statement--multi-result looks promising. If you want to give it a try, go for it. Will definitely merge if it works.

**Comment by raphaeljlps** [comment]
okay, @mattes I will start to work on it soon.

**Comment by alecha** [comment]
I'd like to use `migrate` as a library in my go package, but I've seen that in the init function you call

`driver.RegisterDriver("mysql", &Driver{})`

and this cause a panic because in the same package I also have to import the mysql package that does the same.

There is a way to prevent that?

Thanks!

**Comment by mattes** [comment]
I'm surprised, because the mysql driver registers with https://github.com/mattes/migrate/blob/master/driver/registry.go which is unrelated from the any other mysql driver.

**Comment by alecha** [comment]
Actually the "mysql" name is used both by your driver and by `go-sql-driver` package, am I missing something? 

https://github.com/go-sql-driver/mysql/blob/master/driver.go

**Comment by daddykotex** [comment]
You can rename the package when you import:
```
import (  
        MysqlDriver  "mysql" //rename
    )
```

**Comment by alecha** [comment]
This won't solve the problem, because in these two files I'm importing they are creating a driver with the same name, as it will panic

https://github.com/go-sql-driver/mysql/blob/master/driver.go : line 148
https://github.com/mattes/migrate/blob/master/driver/mysql/mysql.go : line 184

**Comment by daddykotex** [comment]
Ok, I misunderstood your problem.

**Comment by mattes** [comment]
Can you send the panic log?

**Comment by alecha** [comment]
`panic: sql: Register called twice for driver mysql`
`goroutine 1 [running]:`
`database/sql.Register(0x71ff90, 0x5, 0xc6c920, 0xafb488)`
`	/usr/local/go/src/database/sql/sql.go:41 +0x181`
`github.com/go-sql-driver/mysql.init.1()`
`	/Users/alessiocavaleri/Documents/Code/go/src/github.com/go-sql-driver/mysql/driver.go:148 +0x71`
`github.com/go-sql-driver/mysql.init()`
`	/Users/alessiocavaleri/Documents/Code/go/src/github.com/go-sql-driver/mysql/utils.go:973 +0x61c`
`github.com/mattes/migrate/driver/mysql.init()`
`	/Users/alessiocavaleri/Documents/Code/go/src/github.com/mattes/migrate/driver/mysql/mysql.go:185 +0x5e`
`github.com/empatica/web_embrace_api/database.init()`
`/Users/alessiocavaleri/Documents/Code/go/src/github.com/empatica/web_embrace_api/database/userWatchdog.go:65 +0x6c`
`github.com/empatica/web_embrace_api/controllers.init()`
`	/Users/alessiocavaleri/Documents/Code/go/src/github.com/empatica/web_embrace_api/controllers/zipperController.go:53 +0x79
main.init()`
`/Users/alessiocavaleri/Documents/Code/go/src/github.com/empatica/web_embrace_api/embrace_api/main.go:75 +0x62`

`goroutine 17 [syscall, locked to thread]:`
`runtime.goexit()`
`	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1`

**Comment by alecha** [comment]
any news?

**Comment by jonaz** [comment]
What about this?
https://github.com/go-sql-driver/mysql#multistatements

**Comment by revett** [comment]
+1

**Comment by dselans** [comment]
Running into the same issue as @alecha.
