### ISSUE TITLE
panic: sql: Register called twice for driver postgres - Using migrate inside go alongside other database code

### ISSUE THREAD

**Issue by micahwedemeyer** [mattes/migrate#100]
I'm trying to use the migrations alongside some other SQL code, and it looks like the Postgres driver is fighting itself in the `database/sql` module.

    panic: sql: Register called twice for driver postgres
    
    goroutine 1 [running]:
    panic(0x4d7cc0, 0xc820079700)
	    /Users/micah/Developer/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
    database/sql.Register(0x68d1a0, 0x8, 0xf04ac8, 0x97cc48)
	    /Users/micah/Developer/Cellar/go/1.6.2/libexec/src/database/sql/sql.go:45 +0x181
    github.com/lib/pq.init.1()
	    /Users/micah/sandboxes/go/src/github.com/lib/pq/conn.go:44 +0x71
    github.com/lib/pq.init()
	    /Users/micah/sandboxes/go/src/github.com/lib/pq/user_posix.go:24 +0x4b0
    github.com/mattes/migrate/driver/postgres.init()
	    /Users/micah/sandboxes/go/src/github.com/mattes/migrate/driver/postgres/postgres.go:127 +0x4a

It's definitely related to

    import _ "github.com/mattes/migrate/driver/postgres"

but I'm not really sure what to do to get around it. For now, I think I'll just shell out to run migrate via the shell.

**Comment by gravis** [comment]
Is this from the command line output, or you are using the lib in a program of yours?
Since a lot of people is already using the lib without this error, I suspect another import somewhere in your in code ;)
Could you grep for `postgres`?

**Comment by micahwedemeyer** [comment]
Yes, I'm using the lib. I'm using it along side: http://jmoiron.github.io/sqlx/

The import looks like:

    import (
        "github.com/jmoiron/sqlx"
        _ "github.com/mattes/migrate/driver/postgres"
        "github.com/mattes/migrate/migrate"
    )

I'm just wondering if there's anything special about using the migrate library alongside other code that is also interacting with a database.

**Comment by gravis** [comment]
we're using sqlx too, but we don't have that issue :(
Could you try with our fork to see if the pb goes away?
import "github.com/gemnasium/migrate/migrate"
(and I'd like to fix that import path later, the trailing "migrate" is a non-sense)

**Comment by micahwedemeyer** [comment]
Hmm, same thing with the gemnasium fork. I guess if no one else is dealing with this, and others are successfully using it alongside sqlx, then there must be something else I'm doing strangely.

Thanks for the help.

**Comment by gravis** [comment]
again, we're using it along with sqlx, so it's something else ;)
What if you remove the import line:

`_ "github.com/mattes/migrate/driver/postgres"`

?

**Comment by gravis** [comment]
I have checked our code, we have these imports:

```
[...]
        _ "github.com/gemnasium/migrate/driver/postgres"
	"github.com/gemnasium/migrate/file"
	"github.com/gemnasium/migrate/migrate"
	"github.com/gemnasium/migrate/migrate/direction"
[...]
```

and I just triggered a new build with success.

**Comment by micahwedemeyer** [comment]
Turns out I don't really need to use the library directly and I can use it from the shell, which is fine. I'll go ahead and close the issue. Thanks for your help!

**Comment by mdp** [comment]
Stumbled across this myself. Make sure you don't have two different versions of the lib/pq getting called. In my case I had 'migrate' coming from $GOPATH, and the rest of the project was vendored using godep, which resulted in a collision between $GOPATH 'lib/pq' and vendored 'lib/pq'.

https://github.com/lib/pq/pull/455
https://github.com/ory-am/dockertest/issues/39
