### ISSUE TITLE
Timestamps instead of auto increments

### ISSUE THREAD

**Issue by mariokostelac** [mattes/migrate#102]
Auto increments are fine for one-man show, but they become a big problem in a team of hundred people doing several migrations a day. DB version just start clashing.

**Comment by AlekSi** [comment]
See #58 and #95.

**Comment by mariokostelac** [comment]
It's a shame :S.

**Comment by AlekSi** [comment]
@mariokostelac Please reopen it – there is no open issue, only pull requests.

**Comment by gravis** [comment]
@mariokostelac you can safely use our fork if needed: https://github.com/gemnasium/migrate
We're using it in production since a few month without issues.
We also have planned some evolution this summer, but we're a bit busy right now.

**Comment by codepushr** [comment]
Ouch... 22 open pull requests and no reactions... is this still maintained by the author?

**Comment by mariokostelac** [comment]
Does not look like that :S.

**Comment by dacamp** [comment]
#73 is also a dup
