### ISSUE TITLE
Unable to connect to Cassandra

### ISSUE THREAD

**Issue by subbu05** [mattes/migrate#107]
./migrate   -url cassandra://127.0.0.1:9042/migs  create migration_file_xyz
2016/07/01 11:38:44 gocql: unable to dial control conn 127.0.0.1:9042: gocql: no response received from cassandra within timeout period
gocql: unable to create session: control: unable to connect to initial endpoints

I have Cassandra running on locahost:9042
$ cqlsh
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.5 | CQL spec 3.4.0 | Native protocol v4]
Use HELP for help.
cqlsh> exit

**Comment by JensRantil** [comment]
Given https://github.com/mattes/migrate/blob/master/driver/cassandra/README.md it looks like @dinedal, @balboah and @pateld982 has contributed Cassandra driver. Maybe they could have some input on this?

**Comment by KevinBusse** [comment]
Try cassandra://127.0.0.1:9042/migs?protocol=4 to force the correct protocol version... You may have to put it into quotes, in the case your shell tries to expand the `?`

**Comment by mattes** [comment]
seems fixed?
