### ISSUE TITLE
Can't run migrate if one node in multi-cassandra cluster is down

### ISSUE THREAD

**Issue by nlacey** [mattes/migrate#108]
If you have a multi-node cassandra cluster, and one node is down, you can't run migrate.
It will error saying it can't reach consistency "ALL"

In Initialize(),  cluster.Consistency is hard coded to ALL,
my patch wraps gocql.ParseConsistency() in a function that will handle the possible panic() and converts an optional environment variable "CASSANDRA_CONSISTENCY" into the consistency value the sys-admin can set

[cassandra.txt](https://github.com/mattes/migrate/files/348426/cassandra.txt)

cassandra.txt is really driver/cassandra/cassandra.go

Thanks for writing an awesome library!

**Comment by skeswa** [comment]
https://github.com/mattes/migrate/pull/112

**Comment by mattes** [comment]
ref: https://github.com/mattes/migrate/pull/114
closing this
