### ISSUE TITLE
Allow schema option

### ISSUE THREAD

**Issue by vporoshok** [mattes/migrate#115]
I've several microservices on single schema. And every microservice migrate it's own table. I would like to set table which will store version of migration for every microservice. Is it possible to change default schema_migrations?

**Comment by gravis** [comment]
So each microservice has its own access to the DB?
You can then put a `schema_migrations` inside the current schema (the one used by your microservice, not `public`), and it's done. What kind DB are you using?

**Comment by vporoshok** [comment]
Postgres

**Comment by vporoshok** [comment]
It is one schema because some services read from all tables, but writers use separated sets of tables.

**Comment by mattes** [comment]
The way I understand this, @vporoshok wants one `schema_migrations` table per schema and I agree that this a very legit concern. 

Right now, it defaults to the `public` schema. Ideally we'd have something like

```
-url="postgres://user@host:port/database?schema=name" 
```

That way, each of your microservices can specify the schema.

**Comment by mattes** [comment]
Closing this in favor of https://github.com/mattes/migrate/issues/4

**Comment by vporoshok** [comment]
yeah! Thank you!
