### ISSUE TITLE
Tag release versions with semver-compliant tags

### ISSUE THREAD

**Issue by neocortical** [mattes/migrate#116]
Hi Matthias, 

Would it be possible to use annotated git tags for new versions? I recently started using Glide (https://github.com/Masterminds/glide) for dependency management for several large projects, and got bitten by the fact that migrate has a single release tag that turned out to be almost two years old. 

I figured it out and everything is fine, but I think semver release tags are beneficial to the Go community and I hope that more package developers adopt them. I'm currently adding them to my own repos.

**Comment by gravis** [comment]
If you're interested: https://gopkg.in/gemnasium/migrate.v1
