### ISSUE TITLE
Driver improvement: Improve documentation of channel

### ISSUE THREAD

**Issue by JensRantil** [mattes/migrate#122]
The `migrate(...)` method on https://godoc.org/github.com/mattes/migrate/driver#Driver states

> The migration function should use the pipe channel to return any errors or other useful information.

To a new developer this is very unclear what type this channel expects and what kind of information should be given to it. Strings? `error` instances? What is "other useful information"? What will it be used for?

Proposal: Clarify. ;)

**Comment by mattes** [comment]
I agree. I think there is some funky stuff going on with channels. This needs to be addressed.

**Comment by mattes** [comment]
>
