### ISSUE TITLE
Clarification between `redo` and `reset`?

### ISSUE THREAD

**Issue by JensRantil** [mattes/migrate#123]
What's the difference between `redo` and `reset`? README states

```
# roll back the most recently applied migration, then run it again.
migrate -url driver://url -path ./migrations redo

# run down and then up command
migrate -url driver://url -path ./migrations reset
```

, but I'm somewhat unsure exactly how they differ.

**Comment by gravis** [comment]
Redo will go 1 step back, and 1 step forward; while reset will go back
until the first migration, and run again all migrations.
