### ISSUE TITLE
Will this repository be maintained going forward?

### ISSUE THREAD

**Issue by dankinder** [mattes/migrate#127]
Hi,

First let me say that I like this tool, it's useful and well-designed. Going through the issues it's clear others agree with me and want to help improve it.

But it seems like no movement has happened on it for quite some time now, so I figured it is worth asking directly: will this repository be maintained? If not it would be nice to declare that up-front and allow others to maintain it or point to a more up-to-date fork that can be considered official/canonical.

It looks like the guys at https://github.com/gemnasium/migrate have been actively reviewing and merging pull requests, so for the time being I'll be pulling from them.

**Comment by gravis** [comment]
I'm afraid so :)

**Comment by JensRantil** [comment]
Does that mean this can be closed, then? ;)

**Comment by dankinder** [comment]
Maybe there is some confusion. I am asking about this specific repository, which for a good while now has received no intention from @mattes. If he's going to ignore these issues and *also* not maintain it then that's unfortunate for all of us, I wish he would do maintain it or pass it along to someone else.

I think only @mattes or someone else with commit rights to this repository is really qualified to answer the question.

**Comment by rodmcelrath** [comment]
I'd like to reiterate the same question.  I've adopted this sometime back.  Easier to give up on it now while my project is still young.  Are we going to see a handoff and advancement, or is it 'dead'?  Dead is a fair answer.  Would just like to know.

**Comment by gravis** [comment]
We're accepting PR, and still maintain our fork (as it is used in production), if you're interested: https://github.com/gemnasium/migrate

**Comment by codepushr** [comment]
Now using @gravis repo, it's calming to know you are using it in production.

**Comment by gravis** [comment]
no, I meant WE're using it (our repo) in production :)

**Comment by codepushr** [comment]
@gravis That's what I meant :) I switched to your repo as it's getting further maintenance.

**Comment by nathany** [comment]
FYI, I sent an email to matthias.kadenbach@gmail.com on December 13th asking about future maintenance. Yet to receive a response. Hoping he's doing alright and just too busy.

**Comment by arekkas** [comment]
He's active on [twitter](https://twitter.com/mkadenbach?lang=de), probably just not interested in the project

**Comment by arekkas** [comment]
![migrate](https://cloud.githubusercontent.com/assets/3372410/21346957/ef31372a-c6a6-11e6-828b-7f4049bfa904.PNG)

**Comment by nathany** [comment]
I need to do the same for open source projects that I maintain.

**Comment by mattes** [comment]
Several people reached out to me recently. I apologize for being silent in the github conversations on this site. I am happy to see that other developers and teams have found this tool to be useful, too.

I am hoping to find some time over the holidays to go through the PRs and issues.

**Comment by danilobuerger** [comment]
@mattes What about after the holidays? If you don't have time to maintain this repo on a continuous basis, that's fine. But please tell us.

**Comment by mattes** [comment]
@danilobuerger obviously this projects needs contributors. I reached out to @gravis. Hoping to chat with him soon.

**Comment by mattes** [comment]
ping @gravis. did you receive my email? unsure if I used the right one?

**Comment by gravis** [comment]
@mattes I haven't received your email, sorry.
To be honest, I don't feel comfortable contributing to this repo anymore. You completely disappeared for a year, leaving this repo and its users in a dead end. 
I don't want to be in this situation again, so we'll continue on our own fork now.
Thanks

**Comment by nathany** [comment]
@gravis That wouldn't still be a problem if @mattes gave you permissions over here, would it?

Or perhaps you could give @mattes commit permission to the gemnasium/migrate repository if development is moved over there.

**Comment by mattes** [comment]
@gravis I understand. Thanks for your honest feedback. Sorry, for letting you down. Closing this ticket for now.
