### ISSUE TITLE
"version" is out of range for type integer 

### ISSUE THREAD

**Issue by goenning** [mattes/migrate#141]
Hi there,

I'd like to use dates as suffix for my migration files, but I just tried and got the following error:
> pq: value "201701182044" is out of range for type integer

Seems like current structure is already expecting unit64, but it's failing somewhere else.

https://github.com/mattes/migrate/blob/master/file/file.go#L36

**Comment by goenning** [comment]
Just tried adding a new testcase to `TestParseFilenameSchema` with the following content
		`{"20170118205923_demo_file.up.sql", "sql", 20170118205923, "demo_file", direction.Up, false},`.

When I run `make test`, it's still passing.
I'd be happy to submit a PR to fix this, but I'm not sure if I'm doing it the right way.

Thanks.

**Comment by mattes** [comment]
Error seems to come from the postgres `pq` driver.

**Comment by goenning** [comment]
Thanks for the hint, I found the issue. It'll continue fail if someone already has the schema table, but the manual fix should be a simple change of column type.

**Comment by mattes** [comment]
thanks for fixing!!
