### ISSUE TITLE
Portability

### ISSUE THREAD

**Issue by caffinatedmonkey** [mattes/migrate#143]
Currently the `migrate` package gets its migrations from a path on the disk. An API which allows migration files to come from other sources (string, byte array) so they can be embedded with tools like [`rice`](https://github.com/GeertJohan/go.rice) would be nice. Most of the abstractions to do this seems to be in [`file/file.go`](https://github.com/mattes/migrate/blob/master/file/file.go). There just needs to be a few changes made. Any thoughs?

**Comment by mattes** [comment]
There had been efforts. ref: https://github.com/mattes/migrate/pull/34 Not sure what the best way forward is here. Open for discussion.
