### ISSUE TITLE
Command to merge several migrations together

### ISSUE THREAD

**Issue by mbesancon** [mattes/migrate#145]
Once projects accumulate lots of migrations, it can be interesting to merge several migrations into one.  
File *1484755949_initial_structure.up.sql*:
```
CREATE TABLE IF NOT EXISTS "user" (
  id uuid PRIMARY KEY,
  firstname varchar(255) NOT NULL,
  lastname varchar(255) NOT NULL,
  email varchar(255) NOT NULL UNIQUE
);
```
File *1484766949_index_email.up.sql*:
```
CREATE UNIQUE INDEX uk_user_email ON "user"(email);
```
  
Merged migration file:
```
-- 1484755949_initial_structure
CREATE TABLE IF NOT EXISTS "user" (
  id uuid PRIMARY KEY,
  firstname varchar(255) NOT NULL,
  lastname varchar(255) NOT NULL,
  email varchar(255) NOT NULL UNIQUE
);
-- 1484766949_index_email
CREATE UNIQUE INDEX uk_user_email ON "user"(email);
```

Same logic on down files.

**Comment by mattes** [comment]
Hi mbesancon, would something like that work for your use-case?

```
cat *.up.sql > `date +%s`_merged.up.sql
cat *.down.sql > `date +%s`_merged.down.sql
```

**Comment by mbesancon** [comment]
looks great for a start, I'll try to write it as a go command with a comment separator between migrations

**Comment by mattes** [comment]
The following one liner adds the filename as a comment:

```
ls *.up.sql | xargs -I{} sh -c '{ echo -- {}; cat {}; } >> merged.up.sql'
```

Looks easy to me. What would be the advantage of having it in `migrate`?
