### ISSUE TITLE
Flag to change the db table name for migrations

### ISSUE THREAD

**Issue by VMitov** [mattes/migrate#161]
I need this for my project. I'm planning to contribute this feature. Do you see any problem in that?

**Comment by todinov** [comment]
Yes, this seems like it will be useful in some cases. +1

**Comment by mattes** [comment]
Which driver are you using?

For postgres:
Database: postgres://host/database_name
Schema: postgres://host/database_name?search_path=public

Did you mean schema?

**Comment by VMitov** [comment]
I'm using postgres and I want to change `tableName  = "schema_migrations"`.

**Comment by mattes** [comment]
I see. Can you check out the latest postgres driver in v3? https://github.com/mattes/migrate/blob/v3.0-prev/database/postgres/postgres.go#L85

Would that do the job?

Out of curiosity. What table name would you prefer?

Also, how do you feel about the naming `x-migrations-table` instead of `migrations-table`?

**Comment by VMitov** [comment]
I have a specific use case where I need 2 separate migration sequences (schema and data) so I don't really care for the name.

**Comment by mattes** [comment]
Interesting. Thanks for letting me know.

**Comment by VMitov** [comment]
What you think? Will a contribution would be accepted?

**Comment by mattes** [comment]
Check out the link, it's already in the postgres driver (v3). v3 should be stable very soon.

**Comment by VMitov** [comment]
I got a chance to check the code and this looks like what we need. Thank you!

**Comment by todinov** [comment]
I just tested this and there seems to be an issue.
I get the following error:
`error: pq: unrecognized configuration parameter "x-migrations-table" in line 0: SELECT CURRENT_DATABASE()`

I am executing the command like this:
`migrate -database "postgres://postgres:password@127.0.0.1:5432/dbname?x-migrations-table=test" -path migrations up`

Am I doing something wrong or is it that postgres doesn't allow parameters it doesn't know about?

**Comment by mattes** [comment]
I added this yesterday and still haven't tested myself. I wasn't aware about this issue. Seems like we need to drop the custom arguments before the url is being send to the actual Open(url string) func. Good catch! I will take care of it.

**Comment by mattes** [comment]
@todinov My latest commit should've fixed it. https://github.com/mattes/migrate/commit/d5746767028736358d22cb3a7f8c65ded428c670

Want to try again?

**Comment by todinov** [comment]
@mattes Yes, it is working without a problem. Thanks for the quick reaction. I will give it a few more tests today, but I don't expect problems.
