### ISSUE TITLE
Can't use extensions in postgresql schema connection

### ISSUE THREAD

**Issue by yudao** [mattes/migrate#174]
Hi,

First thanks a lot for your great efforts!

I've found a problem when I'm trying to use extensions with postgresql with schema connection (I want to have the migration table in my schema cause every micro services got his own versioning):

```sql
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE chila.users (
  id        serial,
  uuid      uuid      DEFAULT uuid_generate_v4(),
  email     text      NOT NULL UNIQUE,
  username  text      NOT NULL UNIQUE,
  firstName text,
  lastname  text,
  avatarURL text,
  createdAt timestamp DEFAULT now()
);
```

```bash
 migrate -url="postgres://localhost:5432/miya?options=+-c+search_path%3Dchila" -path ./postgres/migrations up 
> 1487685963_add_extension_uuid-ossp.up.sql
> 1487685995_add_table_users.up.sql
ERROR 42883: function uuid_generate_v4() does not exist
````
But when I'm trying to achieve the same process with no schema:

```bash
migrate -url="postgres://localhost:5432/miya" -path ./postgres/migrations up
> 1487685963_add_extension_uuid-ossp.up.sql
> 1487685995_add_table_users.up.sql

0.1070 seconds
````

So there is a way to achieve it in schema (I have maybe failed to read the docs and the code) or it's a real fix to ask ?

Thanks a lot.

Yu.

**Comment by mattes** [comment]
I didn't have time to look into this in detail, yet. Could you give me a favor and confirm that this happens with the latest v3 release candidate, too?

https://github.com/mattes/migrate/releases/tag/v3.0.0-rc0
https://github.com/mattes/migrate/tree/v3.0-prev/cli

```
migrate -path ./postgres/migrations -database 'postgres://localhost:5432/miya?search_path=chila' up
```

**Comment by yudao** [comment]
Ok. I've checkout the tag v3.0.0-rc0 and apply go install.
It's working, so the problem is in the default got get version (I don't know which one is it).

Thanks a lot for your time.

Best regards,

Yu.

**Comment by mattes** [comment]
Yes, `go get` fetches from master branch. v3 should be released very soon.
