### ISSUE TITLE
Allow to configure `schema_migrations` table name

### ISSUE THREAD

**Issue by vearutop** [mattes/migrate#175]
In my case database is shared between several applications with partial data ownership. Each application has its own migrations. Using single `schema_migrations` table is not possible for tracking multiple migration streams. I'd like to have this table name configurable, so that I can specify a unique name for each app.

**Comment by mattes** [comment]
dup: https://github.com/mattes/migrate/issues/161 

@vearutop v3 supports this.

**Comment by vearutop** [comment]
Could you confirm `v3` supports this for `mysql` too?

**Comment by mattes** [comment]
the mysql driver is not yet implemented

**Comment by mattes** [comment]
@vearutop I just pushed an update that includes the mysql driver. Do you mind testing? 

https://github.com/mattes/migrate/commit/be1ba9204a3b0fcd5c49e7c3181e1a649b26333d

**Comment by vearutop** [comment]
I've `make build-cli` on revision `be1ba92`, but when I'm trying to use the tool I receive an error
```
./migrate.darwin-amd64 -database=mysql://root:@tcp\(localhost:3306\)/test_db up
error: no scheme
```
```
./migrate.darwin-amd64 -database=mysql://root:@tcp\(localhost:3306\)/test_db??x-migrations-table=my_table up
error: no scheme
```

Am I doing something wrong?

**Comment by mattes** [comment]
So sorry, there was a bug in `ensureVersionTable`. I just fixed it and tested again myself.
https://github.com/mattes/migrate/commit/1f37f41ee8c7d69a3d835f2ed60d054c9407b85d#diff-b3d7d27134a0bcb9b24a9b90943bf404R295

```
./migrate.darwin-amd64 -database 'mysql://root:root@tcp(localhost:32795)/public' -path $PWD/migrations up
```
