### ISSUE TITLE
Version doesn't close the connection

### ISSUE THREAD

**Issue by chrisaxiom** [mattes/migrate#179]
Repeatedly hitting the `Version` call will quickly exhaust the database connection limit resulting in `pq: sorry, too many clients already`

**Comment by mattes** [comment]
v3 fixed this

**Comment by mattes** [comment]
closing this. thanks for the PR! I highly recommend checking out v3 before committing to v1. :-)

**Comment by chrisaxiom** [comment]
@mattes is v3 stable / ready for production?

**Comment by mattes** [comment]
We use the postgres driver in prod without issues at this point. Unfortunately v3 didn't have as many eyes on it as v1 yet, so it's likely that there are still bugs. That being said, the core migrate package has already better testing than v1.
