### ISSUE TITLE
Exit 1 when no changes

### ISSUE THREAD

**Issue by sagikazarmark** [mattes/migrate#182]
When there are no changes, migrate returns with exit code 1. Is this intended? I don't necessarily see it as an error.

Version: 3.0-rc2

**Comment by mattes** [comment]
Agreed. I'm going to change it to return 0.

**Comment by sagikazarmark** [comment]
Awesome, thanks!

**Comment by mattes** [comment]
Just pushed an update. @sagikazarmark can you verify https://github.com/mattes/migrate/commit/c03b03c9090e236bdf277ea78111163c949ceac7 has the expected behavior now. Thanks!

**Comment by sagikazarmark** [comment]
Works like a charm, thanks! Can we expect an rc3 or no more RCs until release?

**Comment by mattes** [comment]
I was hoping to include the cassandra driver in the next RC. Hoping to find some time over the weekend to get started on that.

**Comment by mattes** [comment]
@sagikazarmark I just pushed the v3.

**Comment by sagikazarmark** [comment]
Awesome, thanks
