### ISSUE TITLE
Cross-compiling for linux from darwin fails

### ISSUE THREAD

**Issue by nathj07** [mattes/migrate#191]
I am currently trying to run:
`go build -o _build/mattes/migrate -ldflags "-w" github.com/mattes/migrate` or even just a straight up `go get -u github.com/mattes/migrate` from my Mac (Darwin) but with `$GOOS=linux` and `$GOARCH=amd64`

Unfortunately, with these env vars set I get:
```
# github.com/mattes/migrate/driver/sqlite3
../../../github.com/mattes/migrate/driver/sqlite3/sqlite3.go:95: undefined: sqlite3.Error
```

Without those envvars being set the build works. If I build directly on a linux box the build works. It only fails on this attempted cross-compile. 

The error message is somewhat perplexing as this  is now up to date and correct against the library in use. So I'm not necessarily indicating a fault here but asking if there is something I am missing in achieving the cross-compile.

**Comment by mattes** [comment]
I don't have an answer unfortunately. Trying to look into it when I have more time. :-/

**Comment by nathj07** [comment]
Ok, I'm gonna tweet it to see if anyone else has any ideas.

This is a great library by the way and has saved me countless headaches since we switched to it from liquibase. So, thanks.

**Comment by mattes** [comment]
I'm glad to hear that. You should consider switching to the latest v3. ;-) 

And please keep me updated on this!

**Comment by nathj07** [comment]
interestingly the issue crops up when cross-compiling for mac from a centos 6.4 box:
```
GOOS=darwin GOARCH=amd64 go build -a -o _build/mattes/migrate github.com/mattes/migrate
# github.com/mattes/migrate/driver/sqlite3
../../../github.com/mattes/migrate/driver/sqlite3/sqlite3.go:95: undefined: sqlite3.Error
```

**Comment by nathj07** [comment]
I'm going to close this issue as there is no need for a fix. The issue comes from the fact that the `go-sqlite3` library uses cgo. 

To get around this I've used a docker container as an intermediate step in my workflow to build this library for the target OS.
