### ISSUE TITLE
Postgres Driver: Not an importable package

### ISSUE THREAD

**Issue by tfmertz** [mattes/migrate#203]
I'm having an issue with v3 and the postgres driver saying:
```
go/src/github.com/mattes/migrate/database/postgres/postgres.go:11:2: import "github.com/mattes/migrate" is a program, not an importable package
```
Then, following the documentation's first example, `migrate.New` is giving an error stating `source driver: unknown driver file (forgotton import?)`

Any idea?

**Comment by stevestotter** [comment]
I've been struggling with this today too but managed to solve it, you need to add to the imports:

`_ "github.com/mattes/migrate/source/file"`

It's not so clear from the error but "file" is missing as a source driver.

@mattes - might want to add this to your second example in the Readme section "Use in your Go project" (https://github.com/mattes/migrate/blob/master/README.md#use-in-your-go-project), at the moment it doesn't work 😉

**Comment by tfmertz** [comment]
Thanks, that is working! The first example was getting the schema from github not a file, now it makes sense.

I'm running into an issue others have mentioned where once the migrations happen pg throws an error
```
column "dirty" does not exist in line 0: SELECT version, dirty FROM "schema_migrations" LIMIT 1
```
I have a postgres container running an init script with some data and tables in it and I assume v3 of migrate now needs a dirty column in a `schema_migrations` table and that data import isn't doing it.

I tried hacking it together and add a `dirty` boolean column to the `schema_migrations` table. The init script only has up to migration 4, so I added version 4, dirty true to the `schema_migrations` table and now I'm getting an error
```
Dirty database version 4. Fix and force version.
```
Is there a way to migrate after a pg data import?

**Comment by stevestotter** [comment]
This is another problem I'm working through at the moment, the (thankfully very active) thread is here: https://github.com/mattes/migrate/issues/202 . Basically an upgrade from v1 to v3 looks broken at the moment...

**Comment by mattes** [comment]
For postgres, I just added https://github.com/mattes/migrate/tree/master/database/postgres#upgrading-from-v1. Let me know if that works for you. Closing this for now, since more or less dup of #202.

**Comment by stevestotter** [comment]
@mattes - can you fix your README.md please for the example above? 

Thanks for the v1 upgrade guide for postgres 👍

**Comment by mattes** [comment]
The example in the Readme is using Github as source driver, hence the filesystem driver (`_ "github.com/mattes/migrate/source/file"`) isn't needed.

I believe using the filesystem driver is a much more common use case. I'll update the example with that.
