### ISSUE TITLE
Bring back `create` command

### ISSUE THREAD

**Issue by mattes** [mattes/migrate#205]
Conversation started in #202 

https://github.com/mattes/migrate/issues/202#issuecomment-297123511
https://github.com/mattes/migrate/issues/202#issuecomment-297278637

**Comment by vort3x** [comment]
Would be nice to use UTC timestamp and not some random/not known numbers in migrations names. And create commands was really useful.

**Comment by leyafo** [comment]
Hi, Everyone. 
v3.0 create command is missing. I made a **temporary** resolved this issue.
It's **temporary** trick, don't use frequently.
`echo -n migration/`date +%s`_migration_name.up.sql|xargs touch`

**Comment by mbellgb** [comment]
This is what I'm using for myself (using `zsh`, but should work with other shells):

```
touch path/to/migrations/$(date +%s)_migration_name.{up,down}.sql
```

`$(date +%s)` is replaced with the number of seconds since the epoch, and `{up,down}` expands the argument into two separate arguments, replacing the first one with `up` and the second with `down`.

**Comment by recurza** [comment]
Is this in progress? I'd be happy to take it up otherwise

**Comment by mattes** [comment]
I don't think someone is working on this. Go for it @recurza! 

So it will be:
`migrate create <name>` outputs `%timestamp-%name.{up,down}`

options:
```
-path <dir> Path to migration files (defaults to current dir)
-ext <extension> optional extension for the file
```

Is this what we are all thinking?

**Comment by mbellgb** [comment]
@mattes I think it'd be better to separate `%timestamp` and `%name` with an underscore rather than a dash, just because I've seen underscores being used more (for example, Rails ActiveRecord migrations). But I think that's otherwise great :+1:

**Comment by mattes** [comment]
agreed @mbellgb

**Comment by recurza** [comment]
Seems like Go favors [camelCase over underscore](https://golang.org/doc/effective_go.html#mixed-caps). How about using a dot? 1497064802.AddXToY.up.sql

**Comment by mattes** [comment]
The camelCase convention from Go doesn't apply to the file names in this case. I think we should go with underscores. Rails migrations use underscores, too.

**Comment by recurza** [comment]
@mattes sure
