### ISSUE TITLE
brew install migrate doesn't work

### ISSUE THREAD

**Issue by mdedgjonaj** [mattes/migrate#206]
I tried to install migrate using brew install and it doesn't work.
Even if you try to search is not available in there.

**Comment by mattes** [comment]
dup #156

**Comment by mattes** [comment]
Are you potentially interested in creating a brew formula?

**Comment by mdedgjonaj** [comment]
I am not familiar with Ruby but will try to create one. I am closing this issue since it is a duplicate.
