### ISSUE TITLE
Will this work with the pgx Go Postgres driver?

### ISSUE THREAD

**Issue by joelpresence** [mattes/migrate#207]
I see that you use `pq` but we are aiming to use [pgx](https://github.com/jackc/pgx).  Do you foresee any conflicts between these two if we use both `migrate` and `pgx` in the same project?

Thanks!  And thanks for making `migrate` available.

**Comment by mattes** [comment]
I don't see any conflicts unless you try to use `WithInstance` for the initialization of the driver.

**Comment by joelpresence** [comment]
Thanks @mattes !  Closing.
