### ISSUE TITLE
Implement Redshift driver

### ISSUE THREAD

**Issue by duffn** [mattes/migrate#208]
The PostgreSQL driver is close but Redshift does not have all the built in functions that Postgres does. I think only a few small tweaks would make it useable for Redshift. 

```
% migrate -verbose -path migrations -database postgres://user:*********@db.qwerty.us-east-1.redshift.amazonaws.com:5439/test up 2
2017/05/03 09:32:49 error: try lock failed in line 0: SELECT pg_try_advisory_lock($1) (details: pq: function pg_try_advisory_lock("unknown") does not exist)
```

**Comment by mattes** [comment]
Looks like `pg_try_advisory_lock` is not supported by Redshift. We could add a flag `x-disable-advisory-lock`?

**Comment by duffn** [comment]
That sounds like a reasonable approach.

**Comment by mattes** [comment]
PR https://github.com/mattes/migrate/pull/222
