### ISSUE TITLE
multi-statement support in mysql driver

### ISSUE THREAD

**Issue by jiangzhu78** [mattes/migrate#211]
We are using 1.3 on production and trying to update to use 3.0.0 We use a lot multi-statement in one migration file. e.g.

```
INSERT INTO `permission` (`object_id`, `object_type`, `action`, `entity_type`)
SELECT 'admin', 'role', `action`, `entity_type`
FROM `permission_check`;

INSERT INTO `permission` (`object_id`, `object_type`, `action`, `entity_type`)
SELECT 'general', 'role', `action`, `entity_type`
FROM `permission_check`
WHERE `entity_type` NOT IN ('admin', 'member', 'team', 'attribute');

INSERT INTO `permission` (`object_id`, `object_type`, `action`, `entity_type`) VALUES
('general', 'role', 'view', 'attribute'),
('general', 'role', 'view', 'team'),
('general', 'role', 'view', 'member'),
('general', 'role', 'view', 'channel');
```

I tried to add line "BEGIN;" before and line "COMMIT;" after as readme under mysql package suggested. However I still get error message says 

> (details: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO `permission` (`object_id`, `object_type`, `action`, `entity_type`) S' at line 3)

Is there a plan to put multi-statement support back in 3.0? Or was my attempt to add "BEGIN" and "COMMIT" incorrect?

Thanks for help

**Comment by mattes** [comment]
Thanks for bringing this up. Can you share the SQL file that's causing problems?

**Comment by jiangzhu78** [comment]
thanks for the reply. one example with "INSERT" was in description (3 sqls in one file). For tables for them, see example below (we have 2 sqls in one file for this)

```sql
CREATE TABLE `permission_check` (
    `entity_type`  VARCHAR(255) NOT NULL,
    `action`       VARCHAR(255) NOT NULL,
    `created_on`   timestamp DEFAULT CURRENT_TIMESTAMP,
    `modified_on`  timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`entity_type`, `action`)
);


CREATE TABLE `permission` (
    `id`              SERIAL,
    `object_id`       VARCHAR(255) NOT NULL,
    `object_type`     VARCHAR(255) NOT NULL,
    `entity_id`       VARCHAR(255) NULL,
    `action`          VARCHAR(255) NOT NULL,
    `entity_type`     VARCHAR(255) NOT NULL,
    `organization_id` VARCHAR(255) NULL,
    `created_on`      timestamp DEFAULT CURRENT_TIMESTAMP,
    `modified_on`     timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (`id`),
    FOREIGN KEY (`entity_type`, `action`) REFERENCES `permission_check` (`entity_type`, `action`),

    UNIQUE KEY `action_entity_type` (`object_id`, `object_type`, `entity_id`, `entity_type`, `action`, `organization_id`),
    INDEX `object_id_type` (`object_type`, `object_id`, `organization_id`),
    INDEX `action_entity` (`entity_type`, `action`, `entity_id`),
    CONSTRAINT `chk_organization_id` CHECK (`object_type` = 'role' OR `organization_id` IS NOT NULL)
);

```

**Comment by pdrosos** [comment]
I have the same issue with version 3. Creating 2 tables inside the same transaction doesn't work:

```sql
CREATE TABLE `synchronizations` (
  `id` CHAR(36) NOT NULL COMMENT 'uuid',
  `state` TINYINT(2) UNSIGNED NOT NULL,
  `response_code` SMALLINT(3) UNSIGNED DEFAULT NULL,
  `response_body` LONGTEXT DEFAULT NULL,
  `error_reason` VARCHAR(255) DEFAULT NULL,
  `started_at` DATETIME DEFAULT NULL,
  `completed_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  KEY `state` (`state`),
  KEY `started_at` (`started_at`),
  KEY `created_at` (`created_at`),
  KEY `updated_at` (`updated_at`)
) ENGINE=InnoDB CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `people` (
  `id` CHAR(36) NOT NULL COMMENT 'uuid',
  `original_id` INT(11) UNSIGNED NOT NULL,
  `current_id` INT(11) UNSIGNED NOT NULL,
  `is_published` TINYINT(1) UNSIGNED NOT NULL,
  `is_hidden` TINYINT(1) UNSIGNED NOT NULL,
  `data` LONGTEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `original_id` (`original_id`),
  INDEX `current_id` (`current_id`),
  INDEX `original_id_current_id` (`original_id`, `current_id`),
  INDEX `created_at` (`created_at`),
  INDEX `updated_at` (`updated_at`)
) ENGINE=INNODB CHARSET=utf8 COLLATE=utf8_unicode_ci;
```
and fails with error:
```
migration failed in line 0: CREATE TABLE ... (details: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE `people` (\n  `id` CHAR(36) NOT NULL COMMENT 'uuid',\n  `origin' at line 20)
```
@mattes is there some workaround or is it a bug and will it be fixed soon?

**Comment by mattes** [comment]
I don't know why it's failing at the moment. Have to look into it. If you find the issue in the meanwhile, please post it here. Thanks!

**Comment by ascotan** [comment]
Having the same problem. Mysql will accept a single statement just fine. However 2 statements cause it to barf with error 1064 (bad syntax)

**Comment by ascotan** [comment]
Just pulled from master and I can verify that 14f7849 fixes this issue

**Comment by mattes** [comment]
thanks for clarification @ascotan. I just released 3.0.1. @jiangzhu78 @pdrosos please make sure to use the latest version. Please re-open if issue persists. Thanks!

**Comment by jiangzhu78** [comment]
Thanks for the fix

**Comment by pdrosos** [comment]
Hi @mattes 
I updated and have the multistatement fix, but unfortunately my migration with the SQL above still fails. 
@jiangzhu78 does it work for you? If yes, may be I don't make something right.

**Comment by pdrosos** [comment]
@mattes it works with me too, the issue was in my code. 
I create the MySQL driver with `mysql.WithInstance` and in this case `multiStatements` must be set to true for the db instance: https://github.com/go-sql-driver/mysql#multistatements

**Comment by mattes** [comment]
thanks for following up. do you mind updating the docs to include this hint?

**Comment by pdrosos** [comment]
Sure, https://github.com/mattes/migrate/pull/239

**Comment by josephbuchma** [comment]
transactions are still not working (go1.8), current master be1b0756056732ed8315516099ed1f3179a15b3a

**Comment by thoslin** [comment]
Thanks @pdrosos ! Save my day. It'd be great if there's a link to this readme in the homepage. I think most people will run into this issue if they try to use it for the first time.
