### ISSUE TITLE
go get github.com/mattes/migrate cannot find package `mssql`

### ISSUE THREAD

**Issue by cyc115** [mattes/migrate#213]
I am having trouble getting the library from github. 

`go get` will yield the following error. I am fairly new to go so it might be something wrong I did on my side too! 

```
>  go get github.com/mattes/migrate

package gopkg.in/mattes/migrate.v1/driver/mssql: cannot find package "gopkg.in/mattes/migrate.v1/driver/mssql" in any of:
        /usr/local/Cellar/go/1.8.1/libexec/src/gopkg.in/mattes/migrate.v1/driver/mssql (from $GOROOT)
        /Users/xjqw46/go/src/gopkg.in/mattes/migrate.v1/driver/mssql (from $GOPATH)
```

I am using Go 1.8.1 

I am working on Notary, and things used to work early last week I think. Building Notary locally also works since go caches the dependency offline. However, Building on CircleCI fails. 

Let me know If there's any more information that I can provide to help!
Thanks in advance!
Mike

**Comment by mattes** [comment]
dup #202

**Comment by cyc115** [comment]
Thanks @mattes
