### ISSUE TITLE
Broken after upgrading ("Unknown column 'dirty' in 'field list')

### ISSUE THREAD

**Issue by fsouza** [mattes/migrate#221]
After upgrading the migrate tool, I'm unable to run my migrations. Are there any migrations for the migrate tool itself? :D 

This was the error when running ``migrate up``:

```
error: Error 1054: Unknown column 'dirty' in 'field list' in line 0: SELECT version, dirty FROM `schema_migrations` LIMIT 1
```

I tried to fix this by adding the ``dirty`` column, then migrate tried to run all migrations again, and it failed running the second migration, and I ended up with the ``schema_migrations`` looking like this:

```
mysql> select * from schema_migrations;
+---------+-------+
| version | dirty |
+---------+-------+
|       2 |     1 |
+---------+-------+
1 row in set (0.01 sec)
```

Before that I had something like this:

```
mysql> select * from schema_migrations;
+---------+
| version |
+---------+
|       2 |
|       3 |
|       4 |
|       5 |
|       6 |
|       7 |
|       8 |
|       9 |
|      10 |
|      11 |
|      12 |
|      13 |
|      14 |
|      15 |
|      16 |
|      17 |
+---------+
16 rows in set (0.01 sec)
```

I wanted to run migration "18", so I solved the issue with ``migrate force 17 && migrate up``.

Have I done something wrong? This was one of my environments, I still have two other environments in the same state, let me know if you want to test something else :)

**Comment by andrew-plunk** [comment]
I have the same problem. What is the correct upgrade path from migrate v1 -> v3?

**Comment by andrew-plunk** [comment]
On postgres 9.4 this works for me @fsouza 
`alter table schema_migrations ADD column dirty boolean not null default false;`

It looks like mysql expects a boolean dirty table also https://github.com/mattes/migrate/blob/448a36c5cbdcc34f348f605a5080b23629c7fbbc/database/mysql/mysql.go#L307

**Comment by fsouza** [comment]
@andrew-plunk I did this, but it didn't fix the issue (I couldn't still run my new migration).

I "fixed" the issue in 3 steps:

1. add the column ``dirty`` to the table ``schema_migrations`` (using the exact same command you used with pg)
1. force the current migration ``migrate force 17`` (the new migration is ``18``)
1. run the new migration ``migrate up``

**Comment by mattes** [comment]
Sorry for the confusion. I added the following steps to make upgrading more clear. 
https://github.com/mattes/migrate/tree/master/database/postgres#upgrading-from-v1

**Comment by fsouza** [comment]
@mattes awesome, thank you!
