### ISSUE TITLE
Go 1.7, travis, failed build: github.com/fsouza/fake-gcs-server/fakestorage

### ISSUE THREAD

**Issue by mattes** [mattes/migrate#233]
@fsouza any thoughts why this would fail with go 1.7?
github.com/fsouza/fake-gcs-server/fakestorage
https://travis-ci.org/mattes/migrate/jobs/233470778#L1031

**Comment by fsouza** [comment]
@mattes ah, ``sort.Slice`` was added in Go 1.8. I just pushed a fix: https://github.com/fsouza/fake-gcs-server/commit/8fc0dc4462a8be17bbabc8ca4d283d273b85116e

Sorry about that.

**Comment by mattes** [comment]
awesome! thanks!
