### ISSUE TITLE
ErrLocked when using migration as lib in go test

### ISSUE THREAD

**Issue by yihuaf** [mattes/migrate#235]
I observed issues with ErrLocked when using the migration as a lib in go test. For each test file, I run `migration.New()` and `migration.Up()` and run `migration.Drop()` and `migration.Close()` during tear down.

If I run a single test, everything seems OK. However, when I run `go test ./...` Test starts to fail with ErrLocked. I also sometimes observe
`pq: duplicate key value violates unique constraint "pg_type_typname_nsp_index" in line 0: CREATE TABLE "schema_migrations" (version bigint not null primary key, dirty boolean not null)` which looks to me multiple create schema migration is run.

I am using the v3 api and the postgres driver. I use a postgres:9.6 container to test.

Am I using at wrong and there are some assumptions I am breaking? Thanks.

**Comment by mattes** [comment]
If tests run in parallel, it's very likely you see `ErrLocked`. That's the expected behavior to make sure only one migration can run at a time.

**Comment by yihuaf** [comment]
Thank you so much. I did not realize the go test run different packages tests in parallel.

For other people's reference, go test -p 1 ./... will fix the this.
