### ISSUE TITLE
`dirty` column in v3

### ISSUE THREAD

**Issue by jney** [mattes/migrate#261]
Hi.

Passing from v1 to v3 we've got the following error:

```
time="2017-07-06T09:19:12Z" level=warning msg="migration up" error="pq: column "dirty" does not exist in line 0: SELECT version, dirty FROM "schema_migrations" LIMIT 1" migrate_source_url="file://migrations" url="postgres://xxx:5432/xxx"
```

Why isn't the table automatically updated?
Did i miss something?

**Comment by mattes** [comment]
For upgrading, please follow: https://github.com/mattes/migrate/tree/master/database/postgres#upgrading-from-v1

Regarding auto upgrading: https://github.com/mattes/migrate/issues/225
