### ISSUE TITLE
Extension is required to work?

### ISSUE THREAD

**Issue by jedborovik** [mattes/migrate#265]
I tried running `up` after creating `1500750789_create_users.up` I got `error: first /Users/jed/whatever/migrations: file does not exist`. It was only after running the create command with `-ext sql` that `up` worked.

Maybe documenting this will help save people like me? My reading of the README was the ext was optional.

**Comment by nicolas33** [comment]
Any extension is required as described in https://github.com/mattes/migrate/blob/master/MIGRATIONS.md

However, I agree the FAQ is misleading.
