### ISSUE TITLE
Missing create option?

### ISSUE THREAD

**Issue by kerak19** [mattes/migrate#283]
Hello. I've installed CLI version of migrate and now i want to create new migration using "migrate create ...".
Problem is i don't have create option.
When i'm using migrate -help i don't even see it:

```
$ migrate -help
Usage: migrate OPTIONS COMMAND [arg...]
       migrate [ -version | -help ]

Options:
  -source          Location of the migrations (driver://url)
  -path            Shorthand for -source=file://path 
  -database        Run migrations against this database (driver://url)
  -prefetch N      Number of migrations to load in advance before executing (default 10)
  -lock-timeout N  Allow N seconds to acquire database lock (default 15)
  -verbose         Print verbose logging
  -version         Print version
  -help            Print usage

Commands:
  goto V       Migrate to version V
  up [N]       Apply all or N up migrations
  down [N]     Apply all or N down migrations
  drop         Drop everyting inside database
  force V      Set version V but don't run migration (ignores dirty state)
  version      Print current migration version
```
As you can see, there's missing create option. I'm using 3.0.1 version.
Is there something wrong with my installation?

**Comment by mattes** [comment]
https://github.com/mattes/migrate/pull/249 what happened to this PR?

**Comment by jigkoxsee** [comment]
Hi @kerak19 
I think v. 3.0.1 doesn't have a create option
Install it via this method [https://github.com/mattes/migrate/tree/master/cli#with-go-toolchain](https://github.com/mattes/migrate/tree/master/cli#with-go-toolchain). You will get a "dev" version

**Comment by JensRantil** [comment]
I guess this issue can be closed?
