### ISSUE TITLE
migrating down from a 001_XXX.down.sql script leaves behind the schema_migrations table with value 1

### ISSUE THREAD

**Issue by bhameyie** [mattes/migrate#35]
Using the cassandra driver, I have noticed that migrating down (even without ever migrating up in the first place) would leave a schema_migration table behind with values 

 versionrow | version
------------+---------
          1 |       1

That's an issue because from that point forward it is no longer possible to truly migrate up. Preferably, it should have set those values to 0.

**Comment by C404** [comment]
@mattes i have the same issue and i'm willing to work on it but what would be the best scenario ?
- Remove `schema_migration` table
- Set `schema_migration` table's values to 0

**Comment by syst3mw0rm** [comment]
I'm able to migrate up and migrate down without any issue. Although, after running `migrate down`, it leaves the following table intact as mentioned.

```
 versionrow | version
------------+---------
          1 |       1
```

If you consider version means next version to be applied, it makes sense. In fact, when you run migrate up, version saved is 1 greater than highest version on migration files i.e, next version to be applied. It can be more intuitive if version equals to current applied version though.

**Comment by alex-fedorov** [comment]
Another point of view on this: Or if the name of the column was `next_version`.
