### ISSUE TITLE
SQLite3 driver slows down build time

### ISSUE THREAD

**Issue by Tonkpils** [mattes/migrate#37]
Using `migrate` package with this commit https://github.com/mattes/migrate/commit/8d39928220ab1352ae5b67b7a9f9605dfdacb20f

sees a slowdown on build time. 

```
$ time godep go build                                                                                
godep go build  18.62s user 0.93s system 107% cpu 18.171 total
```

Compared to the build before the sqlite driver was added:

```
$ time go build
go build  0.55s user 0.09s system 97% cpu 0.660 total
```

That's a sever slowdown for apps that don't use `sqlite`

**Comment by mattes** [comment]
Looks like the download takes quite long:

```
mattn $ time go get -u -v github.com/mattn/go-sqlite3
github.com/mattn/go-sqlite3 (download)
github.com/mattn/go-sqlite3

real	1m44.899s
user	0m18.065s
sys	0m0.887s

mattn $ time go get -u -v github.com/mattn/go-sqlite3
github.com/mattn/go-sqlite3 (download)

real	0m1.520s
user	0m0.136s
sys	0m0.081s
```

Can you confirm its the download for you, too?

**Comment by Tonkpils** [comment]
The download does take quite a bit 

```
$ time go get -d github.com/mattn/go-sqlite3
go get -d github.com/mattn/go-sqlite3  0.23s user 0.09s system 7% cpu 4.150 total
```

But the build time of that package is also very slow

```
go-sqlite3 [master ♥] % time go build
go build  16.91s user 0.52s system 99% cpu 17.510 total
```

All together

```
$ time go get -u -v github.com/mattn/go-sqlite3
github.com/mattn/go-sqlite3 (download)
github.com/mattn/go-sqlite3
go get -u -v github.com/mattn/go-sqlite3  17.21s user 1.00s system 77% cpu 23.658 total
```

**Comment by mattes** [comment]
Interesting, because here its just:

```
time go build

real	0m0.061s
user	0m0.038s
sys	0m0.019s
```

**Comment by mattes** [comment]
Not sure how to fix this. Any ideas?

**Comment by Tonkpils** [comment]
I brought this issue up here because that's where the driver was added but I don't think this is an issue with this package. If it's ok, I'll bring it up with the driver's package maintainer and see what fix we can come up on that end. 

This can be closed, I'll reference it from the issue on their repo.

**Comment by Tonkpils** [comment]
After reading around, it really seems there's not a simple solution. Go `build/install` caches the results. Doing multiple builds only slows down on the first time. However, using `godep go build` does not and recompiles the packages every time and hence the slow down. I wonder it would be possible to do some sort of conditional compilation. It seems like an issue for people not wanting to use `sqlite3` but I don't know of the top of my head. I'll do a bit more research and play around see of a good workaround for us.

I'll close this for now but feel free to re-open if you want to attempt to get other ideas.

**Comment by mattes** [comment]
Maybe we could use an approach like the official database/sql package?

**Comment by Tonkpils** [comment]
How would you envision that looking? It sounds like a good idea.

**Comment by mattes** [comment]
```go
import (
  "github.com/mattes/migrate/migrate"
 "github.com/mattes/migrate/driver/mysql"
)

func main() {
  mysql.MigrateUp(...)
}
```

The binary ``migrate`` would still include all drivers.

**Comment by Tonkpils** [comment]
@mattes that actually sounds like a good solution.
