### ISSUE TITLE
UpSync doesn't tell if migrations have been run

### ISSUE THREAD

**Issue by yannh** [mattes/migrate#53]
Hello, and thanks for migrate! I am using it as a library, but it is awfully silent when successful. I'd be interested to know, if there is no errors, if any migrations have actually been run, and if possible, which files. Additional information such as how long each took wouldn't hurt either :)

As to "Were any migrations run" and "how many" we could return an array of nil errors  instead of just nil if the migration has been successful, and generally throw "nil" in the pipe if a migration works fine.

A larger refactor would be to throw a "MigrationResult struct { error, time.Duration}" or similar in the pipe instead of an error.. Would you consider such a pull request? What do you think would be a good solution? 

Thanks!

**Comment by robzienert** [comment]
+1

**Comment by mattes** [comment]
I would recommend using the async `Up()` func instead and listen for events on the pipe, see [example](https://github.com/mattes/migrate/blob/master/main.go#L167). 

It would be nice if [file.File](https://github.com/mattes/migrate/blob/master/file/file.go#L28) returned some stats, agreed.

**Comment by mattes** [comment]
https://github.com/mattes/migrate/issues/122#issuecomment-268712842
