### ISSUE TITLE
[Question] are go migrations planned?

### ISSUE THREAD

**Issue by raphaeljlps** [mattes/migrate#55]
Hey @mattes I want to ask if there is a plan to support go migrations like in the Goose library,
at work we are needing to convert data from different formats and it would be cool if there is a way to do this using go migrations.

Anyway, if there is no plan and as we are needing this, would you accept a PR to add support for it ?
we are planing to take this effort for ourself if needed.

**Comment by mattes** [comment]
What do you mean with `go migrations`? :-)

**Comment by raphaeljlps** [comment]
sorry if I wasn't clear, I mean go migrations like in the goose https://bitbucket.org/liamstask/goose/src/8488cc47d90c8a502b1c41a462a6d9cc8ee0a895?at=master

e.g. from Goose

Go Migrations
A sample Go migration looks like:

```go
package main

import (
    "database/sql"
    "fmt"
)

func Up_20130106222315(txn *sql.Tx) {
    fmt.Println("Hello from migration 20130106222315 Up!")
}

func Down_20130106222315(txn *sql.Tx) {
    fmt.Println("Hello from migration 20130106222315 Down!")
}
```
Up_20130106222315() will be executed as part of a forward migration, and Down_20130106222315() will be executed as part of a rollback.
