### ISSUE TITLE
Driver 'postgres' not found. using CLI

### ISSUE THREAD

**Issue by nickmarx12345678** [mattes/migrate#64]
Haven't updated anything server side recently, but all of a sudden am running into a missing postgres driver error on my CI server

```
Semaphore: ~/tagkey-backend $ psql tagkey_test
psql (9.4.5)
Type "help" for help.

tagkey_test=# \q
Semaphore: ~/tagkey-backend $ echo $DATABASE_URL
postgres://runner:semaphoredb@localhost/tagkey_test?sslmode=disable
Semaphore: ~/tagkey-backend $   migrate -path=./sql -url=$DATABASE_URL up
Driver 'postgres' not found. 


0.0008 seconds
Connection to 136.243.35.101 closed.
```

**Comment by bfosberry** [comment]
I have the same issue, how do I specify the driver on the command line?

**Comment by bfosberry** [comment]
to replicate 

```
$ docker run -it golang:1.5.0
$ go get -u github.com/mattes/migrate
$ migrate -url postgres://1.2.3.4:1234 -path ./ up
```

**Comment by hdonnay** [comment]
Having this issue when using the package.

**Comment by nickmarx12345678** [comment]
related to https://github.com/mattes/migrate/pull/54 ?

**Comment by mattes** [comment]
Yes, related. :-/ 
We forgot to update https://github.com/mattes/migrate/blob/master/main.go#L6 to include the drivers.

**Comment by RobWC** [comment]
Same issue with MySQL 

Driver 'mysql' not found

**Comment by RobWC** [comment]
Thank you!

**Comment by charyorde** [comment]
Is this fix in the latest release?

**Comment by charyorde** [comment]
I'll like to know the cause of this, as I'm also getting the error `Driver '' not found`.

I'm using Cassandra. I did manually installed the cassandra driver `go get github.com/mattes/migrate/driver/cassandra`. Not luck!

**Comment by victorphamdeveloper** [comment]
@charyorde Any update on the above issue ?

**Comment by charyorde** [comment]
I ended up dumping it for a custom solution.

**Comment by bfosberry** [comment]
You could try forking and force loading the Cassandra driver
