### ISSUE TITLE
I must be doing something stupid...

### ISSUE THREAD

**Issue by joncrlsn** [mattes/migrate#67]
A program very similar to this used to work maybe a year ago.   After updating with ```go get -u``` it now does not find the sqlite3 driver:   "Driver 'sqlite3' not found."   What am I doing wrong?

( I updated both the go-sqlite3 driver and the migrate library to make sure I had the latest.  Thank you in advance for helping a poor sod.  :-)

```
package main

import (
	"github.com/mattes/migrate/migrate"
	_ "github.com/mattn/go-sqlite3"
	"log"
)

func main() {
	allErrors, ok := migrate.ResetSync("sqlite3://temp.db", "./migrations")
	if !ok {
		log.Println("Error migrating schema", allErrors)
		return
	}
}
```

**Comment by mattes** [comment]
You need to import the driver explicitly now. See #54 

```go
import (
    "github.com/mattes/migrate/migrate"
   _ "github.com/mattes/migrate/drivers/sqlite3"
    "log"
)
```

**Comment by joncrlsn** [comment]
Thank you!
