### ISSUE TITLE
MySQL Driver takes a long time to compile

### ISSUE THREAD

**Issue by nerdyc** [mattes/migrate#68]
Incorporating this project into my own has caused compilation to take 30-ish seconds or more. The root cause is compiling the Go MySQL driver, which seems to compile C code it needs.

Since I'm using Postgres, this is a pain. Is there any way to make that dependency optional?

**Comment by waterlink** [comment]
It should be already optional. Recently this landed: #54

Though this only works if you are using `migrate` as the library, not the CLI tool. CLI tool still compiles all drivers.

**Comment by nerdyc** [comment]
Worked perfectly, I just hadn't updated since that landed. Thanks!
