### ISSUE TITLE
Please increase the Release version number, as importing using gopkg.in gets a broken CLI

### ISSUE THREAD

**Issue by michael-go** [mattes/migrate#69]
after running `go get -u gopkg.in/mattes/migrate.v1`, the `migrate` CLI fails with: `Driver 'postgres' not found`. 

I see this issue was fixed in a recent commit: 
https://github.com/mattes/migrate/commit/f5053fbe297728f89b2842d4b2bf0b4e990d19f0

I don't know exactly which git revision is fetched from gopkg.in, but I'm sure its before the commit above.

releasing v1.2.1 or v1.3.0 will fix it (I tested it on my fork)

Thanks

**Comment by revett** [comment]
+1

**Comment by mattes** [comment]
yes. 

ref #116
