### ISSUE TITLE
Passing existing *sql.DB to migrate

### ISSUE THREAD

**Issue by dcelasun** [mattes/migrate#71]
I'm trying to pass an existing `*sql.DB` to migrate for integration testing purposes. This isn't necessary with most databases, but it is needed with sqlite's `:memory:` database.

So maybe we could have 3 new functions that take `sql.DB` pointers instead of URLs, like this:

``` go
UpSyncWithDB(db *sql.DB, migrationsPath string) (err []error, ok bool)
DownSyncWithDB(db *sql.DB, migrationsPath string) (err []error, ok bool)
ResetSyncWithDB(db *sql.DB, migrationsPath string) (err []error, ok bool)
```

What do you think?

**Comment by mattes** [comment]
Interesting idea! Would you still call [`Close()`](https://github.com/mattes/migrate/blob/master/driver/mysql/mysql.go#L47) on the db object?

**Comment by dcelasun** [comment]
In my particular use case (integration tests), yes, after all tests are done I would call [Close()](https://github.com/mattn/go-sqlite3/blob/e969434e25f30ad4d75486b5300808bd4ec29dbd/sqlite3.go#L707). But that should be the responsibility of the caller, `migrate` shouldn't close a connection it didn't open by itself.

**Comment by tcurdt** [comment]
+1

**Comment by dcelasun** [comment]
@mattes Would you be willing to merge a PR for this?

**Comment by lpar** [comment]
I would have liked this, as I already had code to locate a database and set up a connection pool using non-URI connection strings. I ended up having to refactor to use URIs in order to avoid unnecessary extra code.

**Comment by dklimkin** [comment]
Can this be merged? I need this workflow too. Thanks.

**Comment by mattes** [comment]
Closing this in favor of https://github.com/mattes/migrate/pull/120
