### ISSUE TITLE
Synchronous versions of migration functions + negroni http server => ctrl-c didn't work

### ISSUE THREAD

**Issue by harobed** [mattes/migrate#75]
Hi, I use [synchronous versions of migration functions](https://github.com/mattes/migrate#usage-in-go) before launch [negroni http server](https://github.com/codegangsta/negroni#getting-started)

When migrate perform some operations, CTRL-C didn't work.
If migrate do nothing, CTRL-C work perfectly.

Have you some idea about my issue ? One bug in migrate and async function ?

Best regards,
Stéphane

**Comment by harobed** [comment]
I found a tip to fix that bug, I use : 

```
	migrate.NonGraceful()
```

**Comment by harobed** [comment]
Maybe append this information in documentation ?

**Comment by leeola** [comment]
I ran into this too. It seems like a bug.. i would expect https://github.com/mattes/migrate/blob/master/migrate/migrate.go#L311 to be set to false after the sync call is done.

What is the expected behavior here?

**Comment by mattes** [comment]
https://github.com/mattes/migrate/issues/122#issuecomment-268712842

**Comment by mattes** [comment]
I think the channel logic needs a rewrite. Closing this for now.
