### ISSUE TITLE
Segmentation fault on Alpine Linux

### ISSUE THREAD

**Issue by ondrowan** [mattes/migrate#76]
You can replicate it by running:
- `docker run -it golang:1.5.2-alpine sh`
- `apk add --update git alpine-sdk`
- `go get github.com/mattes/migrate`
- `migrate`

From what I've tried, it doesn't happen on OSX, Ubuntu or Debian.

**Comment by raizyr** [comment]
This is probably because https://github.com/mattn/go-sqlite3 is CGO.  Alpine linux uses musl libc rather than glibc.  If you don't need sqlite you may be able to work around it by forking and removing the drivers you don't need.

**Comment by danilobuerger** [comment]
I just tried running migrate on alpine 3.3. Works without a problem for me.

**Comment by cyli** [comment]
I am also seeing this issue on `golang:1.6.0-alpine`, which is based on alpine 3.3.

```
$ strace /go/bin/migrate 
execve("/go/bin/migrate", ["/go/bin/migrate"], [/* 14 vars */]) = 0
arch_prctl(ARCH_SET_FS, 0x7fac21441da8) = 0
set_tid_address(0x7fac21441de0)         = 12
mprotect(0x7fac21440000, 4096, PROT_READ) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0x55961ac54f00} ---
+++ killed by SIGSEGV +++
Segmentation fault
```

Output from running `gdb /go/bin/migrate`:
```
Reading symbols from /go/bin/migrate...done.
Loading Go Runtime support.
(gdb) r
Starting program: /go/bin/migrate 

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7d93531 in ?? () from /lib/ld-musl-x86_64.so.1
(gdb) bt
#0  0x00007ffff7d93531 in ?? () from /lib/ld-musl-x86_64.so.1
#1  0x0000000000000000 in ?? ()
(gdb) quit
```

I notice that https://github.com/golang/go/issues/14476 indicates a segfaulting issue on linux/386 binaries, but I'm seeing this on linux/amd64 too.

**Comment by mattes** [comment]
closing this for now

**Comment by monokrome** [comment]
Not sure if this helps, but I just ran into this and installed `musl musl-dev musl-dbg musl-utils` in order to begin a debug session and the container started working with those packages.

I'm guessing something to do with musl-utils solved this problem?
