### ISSUE TITLE
Unique driver FilenameExtension()

### ISSUE THREAD

**Issue by mattes** [mattes/migrate#8]
Drivers like PostgreSQL, MySQL, ... would usually expect migration files that end with `.sql`. This might be a problem in `ReadMigrationFiles(..)` ([link](https://github.com/mattes/migrate/blob/master/file/file.go#L167)) where it scans a directory for files with the given filename extension regex. 

Maybe we should drop the filename extension parsing and just use all files from that given directory?

**Comment by 13k** [comment]
Pardon my ignorance, but why would somebody mix migrations from different drivers in the same directory?

Is there any support for running generic migrations + driver-specific-only migrations?

For example: `001_create_users.generic` creates `users` using standard SQL, while `002_create_users_indexes.mysql` creates indexes for `users` using MySQL-specific SQL and `003_create_users_indexes.postgres` creates indexes for `users` using Postgres-specific SQL. And then when you `migrate -url mysql://... up` it would run 001 and 002, skipping 003, whereas running `migrate -url postgres://... up` would run 001 and 003, skipping 002.

Besides the above, I don't see any gains in maintaining migrations for multiple drivers in the same directory, or am I missing something?
