### ISSUE TITLE
Move drivers to own repository

### ISSUE THREAD

**Issue by danilobuerger** [mattes/migrate#82]
When go getting or using a package manager, migrate comes with all current drivers which trigger recursive gets on their dependencies. One will end up with unneeded database drivers. A better solution would be like database/sql does. We could then do

```
go get github.com/mattes/migrate
go get github.com/mattes/migrate-drivers/postgres
```

And end up with only the postgres driver (and dependencies) instead of the whole bunch

**Comment by gravis** [comment]
It's done, we can close this.
Driver are loaded on-demand only now: https://github.com/mattes/migrate/blob/master/main.go#L14

**Comment by danilobuerger** [comment]
@gravis This doesn't seem to be fixed. 

```
$ go get -u -v github.com/mattes/migrate
github.com/mattes/migrate (download)
github.com/fatih/color (download)
github.com/mattn/go-colorable (download)
github.com/mattn/go-isatty (download)
github.com/gocql/gocql (download)
github.com/golang/snappy (download)
github.com/hailocab/go-hostpool (download)
Fetching https://golang.org/x/net/context?go-get=1
Parsing meta tags from https://golang.org/x/net/context?go-get=1 (status code 200)
get "golang.org/x/net/context": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context?go-get=1
get "golang.org/x/net/context": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
Fetching https://gopkg.in/inf.v0?go-get=1
Parsing meta tags from https://gopkg.in/inf.v0?go-get=1 (status code 200)
get "gopkg.in/inf.v0": found meta tag main.metaImport{Prefix:"gopkg.in/inf.v0", VCS:"git", RepoRoot:"https://gopkg.in/inf.v0"} at https://gopkg.in/inf.v0?go-get=1
gopkg.in/inf.v0 (download)
github.com/go-sql-driver/mysql (download)
github.com/lib/pq (download)
github.com/mattn/go-sqlite3 (download)
```

All drivers are downloaded on go get.

**Comment by gravis** [comment]
You're right, go get -u will fetch every dependencies :(

**Comment by danilobuerger** [comment]
@gravis thats why i suggested moving the drivers to their own folders. then one could do:

```
import (
	_ "github.com/mattes/migrate/postgres"
	"github.com/mattes/migrate/migrate"
)
```

**Comment by gravis** [comment]
Unfortunately, I'm not a maintainer of this project :(

**Comment by danilobuerger** [comment]
I wonder if @mattes still wants to maintain it anyway, having so many open issues and prs.

**Comment by gravis** [comment]
I'm maintaining the fork for [gemnasium](https://github.com/gemnasium/migrate), but I try to stay close to this repo, to cherrypick updates. If we start to break things, I will probably also break the organization of the package, of the the CLI in its own package, instead of the root of the project.

**Comment by nathany** [comment]
@danilobuerger This issue can be solved another way with better package management tooling, which allows migrate to continue to live in one repo with all the drivers.

See https://github.com/gemnasium/migrate/issues/19#issuecomment-266878587
