### ISSUE TITLE
Make migrate up auto-detect Cassandra keyspace

### ISSUE THREAD

**Issue by charyorde** [mattes/migrate#83]
Nice tool

Please make `migrate` auto detect the Cassandra keyspace when executing CQL script.

For example, this doesn't work
`CREATE TABLE test(id text)`

This works:
`CREATE TABLE keyspace.test(id text)`

Alternatively, add `-k` option to `migrate cli`

**Comment by JensRantil** [comment]
I think auto-detection sounds a bit scary. Better to be explicit when it comes to migration scripts if you ask me.

**Comment by cgilling** [comment]
Doesn't the cli already require you to put a keyspace in the connection url? This is from the documentation found [here](https://github.com/mattes/migrate/tree/master/driver/cassandra):
```
migrate -url cassandra://host:port/keyspace -path ./db/migrations up
```

I tried not putting a keyspace and got a panic, when I wrote my test migrations without mentioning the keyspace in the migrations themselves and ran it against a new keyspace that I had just created everything worked just fine for me

**Comment by JensRantil** [comment]
@cgilling Yes, it's required and I meant I think that's preferable to autodetecting it.

**Comment by nathany** [comment]
Yes, the keyspace is required in the CLI. There should be no need to specify it with CREATE TABLE. I'm using the [Gemnasium fork](https://github.com/gemnasium/migrate) with Cassandra and don't see this as a problem.

**Comment by mattes** [comment]
please re-open if this should be considered as feature.
