### ISSUE TITLE
Support go code migrations

### ISSUE THREAD

**Issue by ralfthewise** [mattes/migrate#88]
Would be nice to be able to do migrations using go code instead of just plain SQL.  If for instance you add a column whose value needs to be calculated in some way that can't be done with just SQL.  This is the only thing preventing me from using this library over something like https://github.com/CloudCom/goose

**Comment by JensRantil** [comment]
The readme mentions planned support for Bash. This would make it possible to execute something like Go if I've understood things correctly. See also #97.

**Comment by mattes** [comment]
See https://github.com/mattes/migrate/pull/34
