### ISSUE TITLE
Issue for bash support

### ISSUE THREAD

**Issue by JensRantil** [mattes/migrate#97]
I notice that support for "Bash" is planned. Is there any issue for that to track?

**Comment by JensRantil** [comment]
@mattes Based on `git blame`, it looks like you were the one that authored "Bash (planned)" in README. Do you know if anyone has anyone started on this? I might be willing to contribute bash/shell support if noone else has done anything on it.

**Comment by JensRantil** [comment]
Ping. Anyone who can answer this? Is there a better channel to ask questions like this than here? IRC? Mailing list?

**Comment by gravis** [comment]
I'm pretty sure bash support is completely stall. Mattes has also disappeared since a while, so I guess this feature won't be available until someone develops it :(

**Comment by JensRantil** [comment]
@gravis Thanks. I'll see if I put together a PR.

**Comment by JensRantil** [comment]
For anyone willing to fix bash support, this is where to start: https://github.com/mattes/migrate/blob/master/driver/bash/bash.go

**Comment by mattes** [comment]
it's on the roadmap, but I don't have an ETA from my side. closing this for now.
