### ISSUE TITLE
Support migrations across multiple databases

### ISSUE THREAD

**Issue by JensRantil** [mattes/migrate#98]
Let's say I have two databases and I'd like to have one migration making changes to multiple databases. `migrate` doesn't handle this right now.

**Comment by gravis** [comment]
You'll have to run `migrate` 2 times, I don't see any reason to add support to multiple DBs in this tool. Let's keep it simple :)

**Comment by JensRantil** [comment]
I like simplicity, but the world is complex! ;)

Example:

Cassandra migrations: 1,3,5
MySQL migrations: 2,4,6

I'd like to run my migrations in the following order: 1,2,3,4,5,6.

**Comment by mattes** [comment]
Agree with @gravis. That feature would add too much complexity to migrate itself.
